UKHSA-Internal/data-dashboard-infra

- terraform/20-app/cloud-front.public-api.tf
I'll follow up with another PR to add some logging later
> Exclude `Accept-Encoding` header in key for cloudfront cache policy

- scripts/_docker.sh
- terraform/20-app/ecs.service.feedback-api.tf
Reconfigures our CLI tooling so that it pulls the application images from the central ECR in the tools account instead of the deprecated one in the dev account
> Pull application images from ECR in tools account

- terraform/20-app/cloud-front.front-end.tf
- terraform/20-app/cloud-front.public-api.tf
- terraform/20-app/locals.tf
- Applies the prod setting for cloudfront TTLs in the public API and FE distributions
- In prod-like envs, TTL is 30 days is set for both
- In dev-like envs, TTL is 1 day for public API and 15 mins for the FE
> Bug/cloudfront misses for public api apply correct ttl/cdd 1861

- scripts/_secrets.sh
- terraform/10-account/.terraform.lock.hcl
- terraform/10-account/versions.tf
- terraform/20-app/.terraform.lock.hcl
- terraform/20-app/alb.feature-flags.tf
- terraform/20-app/api-keys.tf
- terraform/20-app/aurora-db.feature-flags.tf
- terraform/20-app/ecs.service.feature-flags.tf
- terraform/20-app/ecs.service.front-end.tf
- terraform/20-app/locals.tf
- terraform/20-app/outputs.tf
- terraform/20-app/passwords.tf
- terraform/20-app/route-53.tf
- terraform/20-app/route-53.wke-account.tf
- terraform/20-app/route-53.wke-others.tf
- terraform/20-app/secret-manager.tf
- terraform/20-app/versions.tf
- terraform/20-app/waf.feature-flags.tf
This includes the following:
- New dedicated aurora db 
- ECS service + load balancer
- Web app firewall in front of the application
- Restricted with the IP allow list
- Admin password & API key generated and saved in 
- DNS records for the unleash admin application
Proxy is not included in this PR and neither is the pull through ECR cache since we’re pulling the image directly from the official unleash docker hub repo for now.
> Add unleash feature flags application

- terraform/20-app/ecs.service.cms-admin.tf
- terraform/20-app/ecs.service.feedback-api.tf
- terraform/20-app/ecs.service.front-end.tf
- terraform/20-app/ecs.service.private-api.tf
- terraform/20-app/ecs.service.public-api.tf
- terraform/20-app/locals.tf
- Adds scheduled autoscaling policies to all ECS tasks in dev environments 
- Scales in at 8pm every night
- Remains scaled in over weekends
- Scales out at 7am every morning
> Add scheduled autoscaling policies to all ECS tasks in dev environments to spin down at 8pm and back up at 7am

- scripts/_cache.sh
Supress exit code 255 timeout that happens we flush the public API cache at the end of the cache flush process.
This is currently resulting in a false negative whereby the task is still running behind the scenes.
> Task/bypass timeouts when flushing caches/cdd 1882

- terraform/20-app/aurora-db.app.tf
Once the aurora replica clusters have been promoted out of the existing RDS clusters, they  can be switched to be primary.
As such it no longer needs to replicate from the RDS.
Also sets the password to be managed and rotated automatically in secrets manager as we were doing before with RDS
> Set aurora db cluster to be primary and manage main password in secrets manager

- terraform/20-app/ecs.service.cms-admin.tf
- terraform/20-app/locals.tf
Canary approach here. Pointing the CMS admin at the aurora db cluster first. It's not seen by users and takes the least amount of traffic so I'm checking to make sure everything here is okay before switching the remaining workloads over
> Task/rollout aurora db part six switch cms admin to aurora db/cdd 1750

- terraform/20-app/lambda.ingestion.tf
Switches the other write workload i.e. the ingestion lambda over to point to the new aurora db cluster
> Switch ingestion lambda to point to aurora db cluster

- terraform/20-app/alb.feature-flags.tf
Opens the ingress access to the feature flags load balancer by default. 
This is very much a temporary workaround whilst we sort out access via security groups
> Open ingress to feature flags by default - temporary workaround to unblock FE. Needs to be rectified via security groups

- terraform/20-app/ecs-jobs/bootstrap-env.tftpl
- terraform/20-app/ecs.jobs.bootstrap-env.tf
The bootrstrap job useds the utility worker which points to the db node used by the private API replica, at least the variable that was previously dedicated for it.
For non-prod envs this is fine because there is only 1 db node i,e. the primary but when its prod-grade envs like perf then its pointed to a reader/secondary replica i.e. read-only. So the write transaction will fail.
This PR overrides the env var to point to the aurora primary
> Point utility worker used by bootstrap job at aurora primary node

- terraform/20-app/cloud-front.front-end.tf
Sets the TTL on the cloudfront distro to be 8 minutes for:
- home page i.e. at `/`
- all adverse weather pages i.e. at `adverse-weather/*`
> Task/customize cdn ttl for weather health alerts/cdd 1963

- .github/workflows/pull-request.yml
- scripts/_secrets.sh
- src/lambda-alarm-notification/index.js
- src/lambda-alarm-notification/index.test.js
- src/lambda-alarm-notification/jest.config.js
- src/lambda-alarm-notification/package-lock.json
- src/lambda-alarm-notification/package.json
- terraform/20-app/cloudwatch-alarms.tf
- terraform/20-app/lambda.alarm-notification.tf
- terraform/20-app/secret-manager.tf
- terraform/20-app/sns.tf
- Adds a new SNS topic 
- Sends the cloudwatch alarms as actions to the SNS topic
- Adds a new lambda function which subscribes the SNS topic
- Adds a new secret in secrets manager for the slack webhook URL
- New lambda function consumes the event from SNS and fires a notification to the alerts slack channel 
- Includes the corresponding unit tests for the lambda function in the unit tests/coverage CI build
> Task/add sns and notification lambda/cdd 1936

- terraform/20-app/.terraform.lock.hcl
- terraform/20-app/s3.canary-logs.tf
- terraform/modules/cloud-watch-canary/cloudwatch.synthetics-canary.tf
- terraform/modules/cloud-watch-canary/iam.tf
- terraform/modules/cloud-watch-canary/script.tf
- terraform/modules/cloud-watch-canary/security-group.tf
- terraform/modules/cloud-watch-canary/vars.tf
- terraform/modules/cloud-watch-canary/versions.tf
This module will be used as follows:
```
module "cloudwatch_canary_front_end" {
source            = "../modules/cloud-watch-canary"
name              = "${local.prefix}-frontend"
vpc_id            = module.vpc.vpc_id
s3_access_logs_id = data.aws_s3_bucket.s3_access_logs.id
s3_logs_destination = {
bucket_id  = module.s3_canary_logs.s3_bucket_id
bucket_arn = module.s3_canary_logs.s3_bucket_arn
}
subnet_ids          = module.vpc.private_subnets
schedule_expression = "rate(0 minute)"
script_path         = "../../src/canary-front-end/index.js"
}
```
> Task/add synthetic canary for front end/cdd 2109

- terraform/20-app/s3.ingest.tf
Delete files with `in/` prefix from ingest bucket after 2 days. We expect these to be processed within minutes, so these are considered 'dead' files
> s3 ingest bucket lifecycle rule for stale `in/` files

- terraform/10-account/iam.terraform-role.tf
This PR adds an IAM role for terraform to assume. Currently there is a role in each account, but they are not managed by terraform, they were handrolled/click-opped into place.
The change will need to be phased because the role needs to be there for terraform to assume. The next step will be to adjust the `assume_role` variable to point to this new role instead.
> Add IAM role for terraform to assume

- terraform/20-app/ecr.tf
- terraform/modules/ecr/data.aws_ecr_image.tf
- terraform/modules/ecr/ecr.tf
- terraform/modules/ecr/local.tf
- terraform/modules/ecr/outputs.tf
- terraform/modules/ecr/provisioner.initial-image.tf
- terraform/modules/ecr/vars.tf
This PR adds the ECRs which only allow immutable tags.
The idea being we'll dual run publishing to these ECRs and when we're ready i.e. all the tooling is in place, we can switch over
> Task/provide ecrs as module  /cdd 1778

- scripts/_docker.sh
This PR adds a couple of helper function that I'm gonna need soon.
These functions can get the tag of the most recent image in a given ECR.
We need this so we can grab that tag and pull the corresponding image from the central ECR in the tools account.
The big caveat now is that doing `uhd docker pull` and then `uhd docker push` in seperate steps is much harder to do now.
Because we would need to pass the resulting tags between those calls and there is a nasty race condition here with the fact that a new image could be pushed in the middle of that:
```
1. uhd docker pull <- Gives us image of tag abc via these helper functions
2. CI/CD pipeline publishes a new image to the central repo
3. uhd docker push <- Gives us image of tag def via the helper functions
So we would run the risk of …
```
> Add helper functions to retrieve the tag of the most recent image in ECRs

- scripts/_docker.sh
Adds the following command to the CLI tooling:
```
uhd docker update <account> <env>
```
As mentioned in https://github.com/UKHSA-Internal/data-dashboard-infra/pull/976 
we can no longer seperate the pull and push commands without passing the image tags between those commands.
This is because there would be a race condition of what the most recent tag is in process between the pull and push commands being called.
> Task/add docker update command/cdd 1777

- README.md
- scripts/_docker.sh
uhd docker build api
uhd docker build backend
uhd docker build back-end
uhd docker build frontend
uhd docker build front-end
uhd docker ingestion
^ are all now valid. Also building the backend image doesn’t also build the ingestion image, that’s now done seperately.
> Task/amend cli tooling for building custom images/cdd 11248

- terraform/20-app/cloud-front.front-end.tf
- Re-adds cloudfront in front of the weather health alert pages, with a lower TTL of 5 minutes.
- Keeps the caching off the proxy endpoints, which means when the CDN refetches content for those pages every 5 minutes, the proxy endpoints will return fresh/live data
> Task/caching for wha/cdd 2207

- terraform/10-account/kms.tf
- terraform/20-app/kms.tf
This PR adds the following KMS keys:
- 1 at the account layer, to encrypt secrets there
- 2 at the app layer, to encrypt secrets there. There are 2 so we can differentiate between secrets needed by the dev team and secrets needed by operators
I'll follow this up by stitching these into the relevant secrets in a follow up PR
> Task/encrypt secrets with kms key/cdd 1457

- terraform/10-account/iam.operations-role.tf
Fixes CDD-2383
This will prevent operations role from SSH'ing into containers but I think that's fine, we don't really need\want that anyway
> Remove broad `PassRole` permission from operations IAM role

- .github/actions/configure-aws-credentials/action.yml
- .github/workflows/production.yml
- scripts/fast-forward-env-branches.sh
- terraform/20-app/locals.tf
- Hooks up the new `auth-dev` environment in the dev account to the CD pipeline.
- Switches the `is_auth` var to true for the `auth-dev` env, meaning we'll leverage Next.js built-in caching for that env and bypass the CDN
To follow up with this, we'll need to reconfigure the caching in front of the private API
> Add `auth-dev` env to CD pipeline

- .github/actions/configure-aws-credentials/action.yml
- .github/workflows/production.yml
- scripts/fast-forward-env-branches.sh
- terraform/20-app/locals.tf
Redeploying to `auth` instead of `auth-dev` as our CLI tooling for well known envs didn't like the `-` character.
> Add `auth` env in dev account to CD pipeline

- .github/workflows/deploy-personal-dev-environment.yml
- scripts/_terraform.sh
This PR updates the personal dev environments workflow so that:
- It takes the name input as the env to be deployed to directly and doesn't try to compute the hash. This means the engineer has to get their env ID ahead of time (I'll set up a seperate workflow for this)
- Updates the CLI tooling so that the CI environment can target the dev account in cases like this
To follow up, I'm going to:
- Set the bootstrap job build to wait for that ECS task to finish, cause right now it is just fire and forget
- When the bootstrap job is finished, flush the caches for that env
- To make things easier for engineers & QA, I'll set up a new workflow to allow us to flush caches for any personal dev environment (this will be seperate to the current one for well known environments)
> Task/take name input as env name/cdd 2448

- .github/workflows/deploy-personal-dev-environment.yml
- scripts/_ecs.sh
- Waits for the bootstrap db job to send an exit signal before closing the CI build
- Flushes the caches for that env straight after the bootstrap job has completed
The next step will be to add a conditional to allow the `bootstrap_database` build to be skipped
> Task/flush caches after bootstrap job/cdd 2448

- .github/workflows/flush-caches-dev-environment.yml
- .github/workflows/flush-caches-well-known-environment.yml
- Adds a new workflow which takes an input of a string and tries to flush the caches for that dev environment (intended for personal dev envs)
- Renames the original flush caches workflow so that it's a bit clearer that it relates to WKEs
> Task/add workflow to flush personal dev env caches/cdd 2448

- .github/workflows/create-personal-dev-environment.yml
- .github/workflows/deploy-personal-dev-environment.yml
- scripts/_gh.sh
- Makes a new workflow which allows us to deploy feature branches from BE & FE to a given dev environment
- Rename the 1st deploy personal env workflow to `Create Personal Dev Environment`, this also includes bootstrapping the db, so is effectively only to be used for new envs, or to 'reset' the data in that db
> Task/add workflow to deploy feature branches/cdd 2448

- scripts/_docker.sh
- Implements `uhd docker update-service <account> <env> <service>` which we can use to pull the latest image from the tools ECR for a specific service and deploy that to the target env.
E.g:
```
uhd docker update-service dev abc12345 back-end
```
Would pull the latest image from the tools repo for the `back-end` service and publish that image to the `abc12345` environment within the `dev` account
> Implement `uhd docker update-service <account> <env> <service>` to pull and publish latest image for specific service

- .github/workflows/deploy-personal-dev-environment.yml
- If the requested branch name is "main" then we leverage the `uhd docker update-service` command to simply pull the pre-existing main image for that service into the target ECR instead of wastfully cutting a new custom image
> Pull latest main image from tools repo if requested branch name is "main"

- .github/workflows/deploy-personal-dev-environment.yml
- Allows us to build and deploy images seperately between the backend and ingestion service from the deploy personal env workflow
> Allow for building and deploying seperate image to `ingestion` service

- scripts/_terraform.sh
- Modifies the `uhd terraform get-dev-workspace-name` command so that:
- If no arg is provided, the input falls back to the `whoami` command as before
- If a name input is provided, it uses that to hash and build the dev env workspace name from
> Allow optional username to be passed into `uhd terraform get-dev-workspace-name` command

- terraform/20-app/ip-allow-lists.tf
- terraform/20-app/waf.cms.tf
- terraform/20-app/waf.ip-allow-set.tf
- Enforces the IP allow list on the CMS WAF regardless of whether its dev or not
> Apply IP allow list to CMS application regardless of environment type

- .github/actions/configure-aws-credentials/action.yml
- .github/workflows/flush-caches-well-known-environment.yml
Allow `perf` env caches to be flushed via the flush caches well known env workflow
> Task/allow flushing caches of perf in workflow/cdd 2526

- terraform/20-app/alb.cms-admin.tf
- terraform/20-app/ecs.service.cms-admin.tf
These PRs strip off the -tg from ALB target group names. I had to add these originally when I did a version bump of the alb terraform module which reimplemented how they handle target groups and listeners. 
Terraform / AWS (I can't remember which) couldn't handle the fact that there were existing target groups with the same name, hence at the time I had to append `-tg` to the target group names everywhere.
These PRs revert that back now because we'll likely hit character limits for the auth pipeline where we need to append some kind of identifier in the name of the ephemeral workspace to distinguish it from the main ci envs
> Reduce name length of ALB target group for CMS admin app

- scripts/_docker.sh
ECR does not handle multi-architecture container images well and as such handles them slightly differently. 
This is an example of how multi-architecture images are displayed at the moment: 
When the provinence setting is turned off as part of the build command the image is then represented as: 
This then works as expected with other commands within uhd. 
Reference to stack overflow article that explains far better than I have: https://stackoverflow.com/questions/77207485/why-are-there-extra-untagged-images-in-amazon-ecr-after-doing-docker-push
> chore: Update the docker build command to turn off the provenance setting

- terraform/20-app/lambda.ingestion.tf
- terraform/20-app/s3.ingest-archive.tf
- Adds a new s3 bucket called `ingest-archive`
- The new bucket comes with versioning. This allows us to see files which have been overwritten for a given file name
- The bucket also implements a policy which reclassifies all inbound files to the glacier storage class, although when we push the files into the bucket, we'll request the glacier storage class, this is more of a fallback type thing
> Add ingest archive bucket c/w file versioning & policy to transfer inbound files to glacier storage class

- terraform/20-app/ecs.service.front-end.tf
- terraform/20-app/ecs.service.private-api.tf
Scale out the FE and private API ECS services to a higher standing load of 6, to help mitigate the memory leak in the fetch library in the FE
> Temporarily scale out FE and private API services

- terraform/20-app/eventbridge.scheduled-scaling.tf
- Shuts down the db clusters 10 mins after the ECS container workloads in the evening
- Restarts the db clusters 30 mins before the container workloads in the morning
- Keeps the clusters offline over the weekend
- The above only applies to non-prod environments
- The staggered shutdown approach is so that the db clusters are always in a healthy state for the containers. Otherwise the containers can end up in a loop, crashing trying to connect to a db which isn't accepting connections
> Add scheduler to shut down db clusters overnight + over weekends for non-prod envs only

- terraform/20-app/ecs.service.private-api.tf
- terraform/20-app/ecs.service.utility-worker.tf
- terraform/20-app/ecs.service.worker.tf
- terraform/20-app/elasticache.private-api.tf
- Adds a new dedicated & physically seperate elasticache 
- Hooks this up to the private API and the workers
The AWS elasticache cluster mode limitation around the master node not really being a true master means that selective deletions / listing of keys in the cache won’t actually give you what you asked for, it will only give you keys for the node that you are currently connected to.
So a simple way around this is to seperate our ephemeral data (charts, tables, etc) from our long lived data (maps) into dedicated redis caches. They can scale independently of one another and we can then also clear the ephemeral cache with the `clear()` call which is a wrapper around the `FLUSHDB` redis command which will propagate the command to all shards in the cluster …
> Add dedicated elasticache to private API for reserved / long-lived data so we can seperate it from ephemeral data in the existing redis cache

- .github/workflows/production.yml
- Drops the `auth-prod`, `auth-sandbox`, `test`, `auth-test`, `perf` & `auth-perf` environments from the CD pipeline
- Keeps the `dpd`, `dev`, `staging` and public dash `prod` environments on the CD pipeline
Once this goes in, I'll do a terraform destroy on the environments which have been dropped from the CD pipeline to save £££
> Drops the `auth-prod`, `auth-sandbox`, `test`, `auth-test`, `perf` & `auth-perf` environments from the CD pipeline
